package net.shadew.json.template;

public enum ExceptionType {
    INCORRECT_TYPES,
    UNDEFINED_VARIABLE,
    UNDEFINED_FUNCTION,
    FUNCTION_PARAMETER_MISMATCH,
    NO_SCOPE_IN_ROOT,
    EXECUTION_EXCEPTION,
    BREAK_CONTINUE_MISMATCH,
    RECURSION,
    FUNCTION_PARAM_MISMATCH
}
