package net.shadew.json.template.parser;

public enum NodeType {
    DOCUMENT,

    EXPR_LITERAL,
    EXPR_VARIABLE,
    EXPR_UNARY_OP,
    EXPR_BINARY_OP,
    EXPR_TERNARY_OP,
    EXPR_HAS_KEY,
    EXPR_IS_TYPE,
    EXPR_LOGIC_OP,
    EXPR_INDEX,
    EXPR_ASSIGN,
    EXPR_INCR,
    EXPR_SLICE,
    EXPR_MEMBER,
    EXPR_INTERPOLATE_STRING,
    EXPR_DO_THEN,
    EXPR_MATCH,
    EXPR_OBJECT,
    EXPR_ARRAY,
    EXPR_SUBTEMPLATE,
    EXPR_CALL_FN,
    EXPR_UNDERSCORE,
    EXPR_DOLLAR,

    ENT_VALUE,
    ENT_KEY_VALUE,
    ENT_VOID_LINE,
    ENT_IF,
    ENT_FOR_IN,
    ENT_FOR_IN_OBJ,
    ENT_FOR_FROM_TO,
    ENT_BREAK,
    ENT_CONTINUE,
    ENT_RETURN,
    ENT_SWITCH,
    ENT_DEF_EXPRESSION_FN,
    ENT_DEF_SUBTEMPLATE_FN,

    BLOCK_ELSE_IF,
    BLOCK_ELSE,
    BLOCK_CASE,

    STRING_INTERPOLATION,
    MATCH_CASE
}
